### 회원가입
POST http://localhost:8085/member/signup
Content-Type: application/json

{
  "name": "suhsaeechan",
  "email": "chan4760@naver.com",
  "password": "chan4760@",
  "phone": "01066667777"
}

### 로그인
POST http://localhost:8085/member/signin
Content-Type: application/json

{
  "email": "chan4760@naver.com",
  "password": "chan4760@@"
}

### token : 토큰정보 : eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJjaGFuNDc2MEBuYXZlci5jb20iLCJyb2xlIjoiUk9MRV9VU0VSIiwiaWF0IjoxNzA2OTQ4MTY5LCJleHAiOjE3MDY5NTg5Njl9.euum1gwD78c_eib_ZtO_FNRLvIfWWoYUPHfcux69YOU

/

### 회원 업데이트
PUT http://localhost:8085/member/update
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJjaGFuNDc2MEBuYXZlci5jb20iLCJyb2xlIjoiUk9MRV9VU0VSIiwiaWF0IjoxNzA2NjI1ODkxLCJleHAiOjE3MDY2MzY2OTF9.aWWcrwX7MJOuWnVZcfxyIPgGuNGz3Pxe6KNhDlR_-6Y
Content-Type: application/json

{
  "name": "saechanUpdate",
  "password": "chan4760@@",
  "phone": "01066660000"
}


### 회원 이메일 업데이트
POST http://localhost:8085/member/changeEmail
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJjaGFuNDc2MEBuYXZlci5jb20iLCJyb2xlIjoiUk9MRV9VU0VSIiwiaWF0IjoxNzA2NjI1ODkxLCJleHAiOjE3MDY2MzY2OTF9.aWWcrwX7MJOuWnVZcfxyIPgGuNGz3Pxe6KNhDlR_-6Y
Content-Type: application/json

{
  "email": "chan4760@nate.com"
}

### 회원 정보 조회
GET http://localhost:8085/member/profile
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJjaGFuNDc2MEBuYXZlci5jb20iLCJyb2xlIjoiUk9MRV9VU0VSIiwiaWF0IjoxNzA2NjI1NjA3LCJleHAiOjE3MDY2MzY0MDd9.iWmNLLDb7RBUKgjNThLNZ7rAmJaleXzYgy-4VT2Pdc0
Content-Type: application/json

### 회원 탈퇴
DELETE http://localhost:8085/member/delete
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJjaGFuNDc2MEBuYXZlci5jb20iLCJyb2xlIjoiUk9MRV9VU0VSIiwiaWF0IjoxNzA2NjIzNzE3LCJleHAiOjE3MDY2MzQ1MTd9.ee-IFbw-z4wTTbzQHQg3aW1SDRmzTiIIdU081Giuv8c
Content-Type: application/json

### 상점 정보 변경
PUT http://localhost:8085/store/update
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJjaGFuNDc2MEBuYXZlci5jb20iLCJyb2xlIjoiUk9MRV9VU0VSIiwiaWF0IjoxNzA2ODA1NDc4LCJleHAiOjE3MDY4MTYyNzh9.1sV7secbWQRf1QqjK84n0pKwbt385S8SB-WsIBkH7rY
Content-Type: multipart/form-data

{
  "name": "상점 이름 변경 테스트",
  "description": "상점 상세내용 변경 테스트",
  "image": "/docs/img/main.png"
}

### 상점 정보 조회
GET http://localhost:8085/store/profile
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJjaGFuNDc2MEBuYXZlci5jb20iLCJyb2xlIjoiUk9MRV9VU0VSIiwiaWF0IjoxNzA2Nzc3MjE3LCJleHAiOjE3MDY3ODgwMTd9.cjGFBJGOLrNobzONvSWUCuCEt-INNUr7LC_L8GtSB7g
Content-Type: application/json

### 상점 이미지 업로드
POST http://localhost:8085/files/upload
Content-Type: multipart/form-data
file=@"/doc/img/main.png"

### 상점 이미지 여러장 업로드
POST http://localhost:8085/files/upload-muliple
Content-Type: multipart/form-data

< file=@/doc/img/main.png
< file=@/doc/img/erd_graph.png


< file=@/doc/img/main.png

### 포인트 내보내기
POST http://localhost:8085/point/withDraw
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJjaGFuNDc2MEBuYXZlci5jb20iLCJyb2xlIjoiUk9MRV9VU0VSIiwiaWF0IjoxNzA2Nzc3MjE3LCJleHAiOjE3MDY3ODgwMTd9.cjGFBJGOLrNobzONvSWUCuCEt-INNUr7LC_L8GtSB7g
Content-Type: application/json

{
  "withDrawAmount": 1000,
  "accountNumber": "3333043333000"
}

### 포인트 충전
POST http://localhost:8085/point/charge
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJjaGFuNDc2MEBuYXZlci5jb20iLCJyb2xlIjoiUk9MRV9VU0VSIiwiaWF0IjoxNzA2Nzc3MjE3LCJleHAiOjE3MDY3ODgwMTd9.cjGFBJGOLrNobzONvSWUCuCEt-INNUr7LC_L8GtSB7g
Content-Type: application/json

{
  "chargeAmount": 50000,
  "accountNumber": "3333043333000"
}


### 포인트 조회
GET http://localhost:8085/point/history/0
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJjaGFuNDc2MEBuYXZlci5jb20iLCJyb2xlIjoiUk9MRV9VU0VSIiwiaWF0IjoxNzA2Nzc3MjE3LCJleHAiOjE3MDY3ODgwMTd9.cjGFBJGOLrNobzONvSWUCuCEt-INNUr7LC_L8GtSB7g
Content-Type: application/json