### 회원가입
POST http://localhost:8085/member/signup
Content-Type: application/json

{
  "name": "suhsaechan",
  "email": "chan4760@naver.com",
  "password": "chan4760@",
  "phone": "01066667777"
}

### 이메일 인증
GET http://localhost:8085/member/email-auth?code=51bef22b240a466a8037e8dfddbcac77
Content-Type: application/json

### 로그인
POST http://localhost:8085/member/signin
Content-Type: application/json

{
  "email": "chan4760@naver.com",
  "password": "chan4760@"
}

### token : 토큰정보 : eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJjaGFuNDc2MEBuYXZlci5jb20iLCJyb2xlIjoiUk9MRV9VU0VSIiwiaWF0IjoxNzA3MjE1NTE2LCJleHAiOjE3MDcyMjYzMTZ9.Dw-oqhlAWIBzNykvwe8Ix6hSMWYjaho9pUDhwH4kfXA


/

### 회원 업데이트
PUT http://localhost:8085/member/update
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJjaGFuNDc2MEBuYXZlci5jb20iLCJyb2xlIjoiUk9MRV9VU0VSIiwiaWF0IjoxNzA3MTIzNTI5LCJleHAiOjE3MDcxMzQzMjl9.dm1pGIAdt8cX5u4oF1Uu2uaqYIrRYmGY5zv0lmLn0TQ
Content-Type: application/json

{
  "name": "saechanUpdate",
  "password": "chan4760@",
  "phone": "+123456789012"
}


### 회원 이메일 업데이트
POST http://localhost:8085/member/changeEmail
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJjaGFuNDc2MEBuYXZlci5jb20iLCJyb2xlIjoiUk9MRV9VU0VSIiwiaWF0IjoxNzA3MTIzNTk2LCJleHAiOjE3MDcxMzQzOTZ9.48dOvlDNeiNa51nwzBoGcILGBv6d2cTClysTtC7cPEc
Content-Type: application/json

{
  "email": "chan4760@nate.com"
}

### 회원 정보 조회
GET http://localhost:8085/member/profile
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJjaGFuNDc2MEBuYXZlci5jb20iLCJyb2xlIjoiUk9MRV9VU0VSIiwiaWF0IjoxNzA3MTIzNTk2LCJleHAiOjE3MDcxMzQzOTZ9.48dOvlDNeiNa51nwzBoGcILGBv6d2cTClysTtC7cPEc
Content-Type: application/json

### 회원 탈퇴
DELETE http://localhost:8085/member/delete
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJjaGFuNDc2MEBuYXZlci5jb20iLCJyb2xlIjoiUk9MRV9VU0VSIiwiaWF0IjoxNzA2NjIzNzE3LCJleHAiOjE3MDY2MzQ1MTd9.ee-IFbw-z4wTTbzQHQg3aW1SDRmzTiIIdU081Giuv8c
Content-Type: application/json

### 상점 정보 변경 (postman에서 확인)
PUT http://localhost:8085/store/update
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJjaGFuNDc2MEBuYXZlci5jb20iLCJyb2xlIjoiUk9MRV9VU0VSIiwiaWF0IjoxNzA3MTIzNTk2LCJleHAiOjE3MDcxMzQzOTZ9.48dOvlDNeiNa51nwzBoGcILGBv6d2cTClysTtC7cPEc
Content-Type: multipart/form-data


### 상점 정보 조회
GET http://localhost:8085/store/profile
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJjaGFuNDc2MEBuYXZlci5jb20iLCJyb2xlIjoiUk9MRV9VU0VSIiwiaWF0IjoxNzA3MTIzNTk2LCJleHAiOjE3MDcxMzQzOTZ9.48dOvlDNeiNa51nwzBoGcILGBv6d2cTClysTtC7cPEc
Content-Type: application/json

### 포인트 내보내기
POST http://localhost:8085/point/withDraw
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJjaGFuNDc2MEBuYXZlci5jb20iLCJyb2xlIjoiUk9MRV9VU0VSIiwiaWF0IjoxNzA3MTIzNTk2LCJleHAiOjE3MDcxMzQzOTZ9.48dOvlDNeiNa51nwzBoGcILGBv6d2cTClysTtC7cPEc
Content-Type: application/json

{
  "withDrawAmount": 5000,
  "accountNumber": "3333043333000"
}

### 포인트 충전
POST http://localhost:8085/point/charge
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJjaGFuNDc2MEBuYXZlci5jb20iLCJyb2xlIjoiUk9MRV9VU0VSIiwiaWF0IjoxNzA3MTIzNTk2LCJleHAiOjE3MDcxMzQzOTZ9.48dOvlDNeiNa51nwzBoGcILGBv6d2cTClysTtC7cPEc
Content-Type: application/json

{
  "chargeAmount": 10,
  "accountNumber": "3333043333000"
}


### 포인트 조회
GET http://localhost:8085/point/history/0
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJjaGFuNDc2MEBuYXZlci5jb20iLCJyb2xlIjoiUk9MRV9VU0VSIiwiaWF0IjoxNzA2Nzc3MjE3LCJleHAiOjE3MDY3ODgwMTd9.cjGFBJGOLrNobzONvSWUCuCEt-INNUr7LC_L8GtSB7g
Content-Type: application/json


### 상품 생성 (postman으로 확인)
POST http://localhost:8085/product/create
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJjaGFuNDc2MEBuYXZlci5jb20iLCJyb2xlIjoiUk9MRV9VU0VSIiwiaWF0IjoxNzA2NzU5NzIxLCJleHAiOjE3MDY3NzA1MjF9.vKQE7QWPumM-WPTQn-NfjkQ33TYDCv67rnue3Ho9eLs

### 상품 수정(업데이트) (postman으로 확인)
PUT http://localhost:8085/product/update
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJjaGFuNDc2MEBuYXZlci5jb20iLCJyb2xlIjoiUk9MRV9VU0VSIiwiaWF0IjoxNzA2NzU5NzIxLCJleHAiOjE3MDY3NzA1MjF9.vKQE7QWPumM-WPTQn-NfjkQ33TYDCv67rnue3Ho9eLs

### 상품 삭제
DELETE http://localhost:8085/product/delete?id=1
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJjaGFuNDc2MEBuYXZlci5jb20iLCJyb2xlIjoiUk9MRV9VU0VSIiwiaWF0IjoxNzA2NzU5NzIxLCJleHAiOjE3MDY3NzA1MjF9.vKQE7QWPumM-WPTQn-NfjkQ33TYDCv67rnue3Ho9eLs

### 상품 조회
GET http://localhost:8085/product/view?id=1
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJjaGFuNDc2MEBuYXZlci5jb20iLCJyb2xlIjoiUk9MRV9VU0VSIiwiaWF0IjoxNzA3MTI1ODY4LCJleHAiOjE3MDcxMzY2Njh9.JU_xScAzQB_NE16vQTOqLZSv16N0Lygp-v1fn_Wxp9g
Content-Type: application/json
