version: '1.8'
services:
  collector-market-app:
    build:
      context: .
      dockerfile: docker/api/Dockerfile
    container_name: collector-market-app
    env_file: config/prod.env
    ports:
      - "8085:8080"
    depends_on:
      - redis
      - solr

  redis:
    image: redis:latest
    container_name: cm-redis
    ports:
      - "6379:6379"

  solr:
    image: solr:8
    container_name: cm-solr
    ports:
      - "8983:8983"
    volumes:
      - ./solr-data:/var/solr
    command:
      - solr-precreate
      - product

  nginx:
    image: nginx:latest
    container_name: cm-nginx
    ports:
      - "85:80"
    volumes:
      - ./docker/nginx/nginx.conf:/etc/nginx/nginx.conf:ro
