version: '1.8'
services:
  collector-market-app:
    build:
      context: .
      dockerfile: docker/api/Dockerfile
    container_name: collector-market-app
#    env_file: ../config/dev.env
    env_file: config/prod.env
#    env_file: ../config/config.env
    ports:
      - "8085:8080"
    depends_on:
      - redis
#      - elasticsearch

  redis:
    image: redis:latest
    container_name: cm-redis
    ports:
      - "6379:6379"

#  elasticsearch:
#    image: docker.elastic.co/elasticsearch/elasticsearch:8.12.1
#    container_name: cm-elasticsearch
#    environment:
#      - "discovery.type=single-node"
#    ports:
#      - "9200:9200"
#      - "9300:9300"

  nginx:
    image: nginx:latest
    container_name: cm-nginx
    ports:
      - "85:80"
    volumes:
      - ./docker/nginx/nginx.conf:/etc/nginx/nginx.conf:ro
